FROM python:3.12.10-slim
WORKDIR /app
COPY requirements.cpu.txt requirements.txt
RUN pip install -r requirements.txt --extra-index-url https://download.pytorch.org/whl/cpu

RUN python -c "from sentence_transformers import SentenceTransformer; \
SentenceTransformer('nomic-ai/nomic-embed-text-v1.5', trust_remote_code=True)"

COPY server.py server.py
CMD ["python", "server.py"]
