FROM python:3.12.10-slim
WORKDIR /app
COPY requirements.cpu.txt requirements.txt
RUN pip install -r requirements.txt --extra-index-url https://download.pytorch.org/whl/cpu

# RUN pip install -U litserve
COPY server.py server.py
CMD ["python", "server.py"]
