FROM python:3.12.10-slim
WORKDIR /app
COPY requirements.cpu.txt requirements.txt
RUN pip install hf-transfer
RUN pip install -r requirements.txt --extra-index-url https://download.pytorch.org/whl/cpu
ENV HF_HUB_ENABLE_HF_TRANSFER=1
COPY server.py server.py
CMD ["python", "server.py"]
